apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chronograf
  namespace: monitoring-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: chronograf
      version: "1.2.5"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    env:
      INFLUXDB_URL: http://influxdb:8086
    # Note: We will use valuesFrom for secrets in the overlay or keep it minimal here
    # For now, let's keep it minimal and assume the secret exists
  valuesFrom:
    - kind: Secret
      name: monitoring-credentials
      valuesKey: INFLUXDB_USERNAME
      targetPath: env.INFLUXDB_USERNAME
    - kind: Secret
      name: monitoring-credentials
      valuesKey: INFLUXDB_PASSWORD
      targetPath: env.INFLUXDB_PASSWORD
