apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
  namespace: monitoring-stack
type: Opaque
stringData:
  INFLUXDB_USERNAME: admin
  INFLUXDB_PASSWORD: change-me-now # In a real scenario, use a strong password
