apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.6.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
