apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: edge-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 10Gi
    storageClass: longhorn-edge
