apiVersion: v1
kind: Secret
metadata:
  # Pattern: <user>.<cluster-name>.credentials
  name: app-user.acid-minimal-cluster.credentials
  namespace: postgres-db
  labels:
    application: spilo
    cluster-name: acid-minimal-cluster
    team: acid
type: Opaque
stringData:
  password: "supersecretpassword"
