apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prod-db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 20Gi
    storageClass: longhorn-ha
  walStorage:
    size: 5Gi
    storageClass: longhorn-ha
  monitoring:
    enablePodMonitor: true
