apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 30m
  values:
    server:
      dev:
        enabled: true
        devRootToken: root
      service:
        type: ClusterIP
    ui:
      enabled: true
