apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  releaseName: cnpg
  targetNamespace: postgresql-operator
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg-oci
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
