apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: "3.12.x"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    args:
      - --kubelet-insecure-tls
