apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: influxdb
      version: "1.1.15"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    image:
      tag: "1.8.10-alpine"
    persistence:
      enabled: true
      size: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chronograf
  namespace: monitoring-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: chronograf
      version: "1.2.5"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    env:
      INFLUXDB_URL: http://influxdb:8086
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: fluent-bit
      version: "0.47.0"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  values:
    config:
      outputs: |
        [OUTPUT]
            Name            influxdb
            Match           *
            Host            influxdb.monitoring-stack.svc.cluster.local
            Port            8086
            Database        fluentbit
            Auto_Create_DB  On
