apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: fluent-bit
      version: "0.47.0"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: fluentbit-values
      valuesKey: values.yaml

