apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: influxdb
      version: "1.1.15"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: influxdb-values
      valuesKey: values.yaml

